/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author renato
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuBarTelaPrincipal = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuItemCadastrarUsuario = new javax.swing.JMenuItem();
        mnuItemAlterarUsuario = new javax.swing.JMenuItem();
        mnuItemExcluirUsuario = new javax.swing.JMenuItem();
        mnuItemPesquisarUsuario = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        mnuItemCadastrarCliente = new javax.swing.JMenuItem();
        mnuItemAlterarCliente = new javax.swing.JMenuItem();
        mnuItemExcluirCliente = new javax.swing.JMenuItem();
        mnuItemPesquisarCliente = new javax.swing.JMenuItem();
        mnuItemSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        mnuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page.png"))); // NOI18N
        mnuArquivo.setText("Arquivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        mnuArquivo.add(jMenuItem1);

        mnuBarTelaPrincipal.add(mnuArquivo);

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        mnuUsuarios.setText("Usuários");

        mnuItemCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        mnuItemCadastrarUsuario.setText("Cadastrar");
        mnuItemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastrarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuItemCadastrarUsuario);

        mnuItemAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        mnuItemAlterarUsuario.setText("Alterar");
        mnuUsuarios.add(mnuItemAlterarUsuario);

        mnuItemExcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
        mnuItemExcluirUsuario.setText("Excluir");
        mnuUsuarios.add(mnuItemExcluirUsuario);

        mnuItemPesquisarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        mnuItemPesquisarUsuario.setText("Pesquisar");
        mnuUsuarios.add(mnuItemPesquisarUsuario);

        mnuBarTelaPrincipal.add(mnuUsuarios);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        mnuClientes.setText("Clientes");

        mnuItemCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_add.png"))); // NOI18N
        mnuItemCadastrarCliente.setText("Cadastrar");
        mnuClientes.add(mnuItemCadastrarCliente);

        mnuItemAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        mnuItemAlterarCliente.setText("Alterar");
        mnuClientes.add(mnuItemAlterarCliente);

        mnuItemExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_delete.png"))); // NOI18N
        mnuItemExcluirCliente.setText("Excluir");
        mnuClientes.add(mnuItemExcluirCliente);

        mnuItemPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        mnuItemPesquisarCliente.setText("Pesquisar");
        mnuClientes.add(mnuItemPesquisarCliente);

        mnuBarTelaPrincipal.add(mnuClientes);

        mnuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        mnuItemSobre.setText("Sobre");
        mnuBarTelaPrincipal.add(mnuItemSobre);

        setJMenuBar(mnuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemCadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenuBar mnuBarTelaPrincipal;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuItemAlterarCliente;
    private javax.swing.JMenuItem mnuItemAlterarUsuario;
    private javax.swing.JMenuItem mnuItemCadastrarCliente;
    private javax.swing.JMenuItem mnuItemCadastrarUsuario;
    private javax.swing.JMenuItem mnuItemExcluirCliente;
    private javax.swing.JMenuItem mnuItemExcluirUsuario;
    private javax.swing.JMenuItem mnuItemPesquisarCliente;
    private javax.swing.JMenuItem mnuItemPesquisarUsuario;
    private javax.swing.JMenu mnuItemSobre;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
